export const CART_ADD_PRODUCT_REQUESTED = '[Cart] PUSH PRODUCT REQUESTED';
export const CART_ADD_PRODUCT_RECEIVED = '[Cart] PUSH PRODUCT RECEIVED';

export const CART_REDUCE_PRODUCT_REQUESTED = '[Cart] REDUCE PRODUCT REQUESTED';
export const CART_REDUCE_PRODUCT_RECEIVED = '[Cart] REDUCE PRODUCT RECEIVED';

export const CART_DELETE_PRODUCT_REQUESTED = '[Cart] DELETE PRODUCT REQUESTED';
export const CART_DELETE_PRODUCT_RECEIVED = '[Cart] DELETE PRODUCT RECEIVED';
