export const PRODUCTS_REQUESTED = '[Products] REQUESTED';
export const PRODUCTS_RECEIVED = '[Products] RECEIVED';

export const PRODUCTS_BY_ID_REQUESTED = '[Products] BY ID REQUESTED';
export const PRODUCTS_BY_ID_RECEIVED = '[Products] BY ID RECEIVED';

export const PRODUCTS_CATEGORY_REQUESTED = '[Products] CATEGORY REQUESTED';
export const PRODUCTS_CATEGORY_RECEIVED = '[Products] CATEGORY RECEIVED';

export const PRODUCTS_BY_NAME_REQUESTED = '[Products] BY NAME REQUESTED';
export const PRODUCTS_BY_NAME_RECEIVED = '[Products] BY NAME RECEIVED';
